### PR TITLE
Free surface

### PR DESCRIPTION
**Pull request by albert-de-montserrat**
Adds free surface stabilization from `Gerya, Taras. Introduction to numerical geodynamic modelling. Cambridge University Press, 2019`., eq. 8.23

The method was first described in:

FEM:
- Kaus, B.J.P., Mühlhaus, H., May, D.A., 2010. A stabilization algorithm for geodynamic numerical simulations with a free surface. Physics of the Earth and Planetary Interiors 181, 12–20. https://doi.org/10.1016/j.pepi.2010.04.007

Staggered FD:
- Duretz, T., May, D.A., Gerya, T.V., Tackley, P.J., 2011. Discretization errors and free surface stabilization in the finite difference and marker-in-cell method for applied geodynamics: A numerical study:  Geochem. Geophys. Geosyst. 12, n/a-n/a. https://doi.org/10.1029/2011GC003567

Introduces a **breaking change**: the time step can no longer be `dt=Inf` when passed into the Stokes solver

### CODE REVIEW

**Comment by albert-de-montserrat** [comment]
Great thanks! I will add it to the miniapps and CI

**Comment by aelligp** [comment]
- [ ] Add polygon / passive tracers to track free surface

**Comment by albert-de-montserrat** [comment]
Test from [Taras book](https://www.cambridge.org/core/books/introduction-to-numerical-geodynamic-modelling/2229E18CAB72D31CA86E51D66948E6D0)


Rayleigh-Taylor instability

**Comment by boriskaus** [comment]
Looks good - do you have a plot of the temporal evolution of the interface as well? I can dig out the digital solution for that to compare

**Comment by albert-de-montserrat** [comment]
I have it somewhere. Was fixing a couple of bugs/setup, will let it run for longer to compare the final geometry, but looks like its working now.

**Comment by albert-de-montserrat** [comment]
Not very high resolution but looks correct

**Pull request merged**
