### PR TITLE
Thermal Stresses 

### PR DESCRIPTION
**Pull request by aelligp**
This adds thermal stresses according to the implementation of Kiss et al. (2023)

```math
\frac{\partial P^{\textrm{tr}}}{\partial \omega}  = - \frac{\partial v_{\textrm{k}}}{\partial x_{\textrm{k}}} + \alpha \frac{dT}{dt} + \beta \frac{P^{\textrm{tr}} - P^{\textrm{old}}}{dt}
```

Few issues persist: 
- We don't solve for density the same way they did 
```math
\rho = \rho^{\textrm{old}} \exp(-\frac{\partial{v_k}}{\partial{x_k}} dt)
```

### CODE REVIEW

**Comment by aelligp** [comment]
Currently, the thermal stresses only work for incompressible rheologies and no free surface in the model setup.

**Comment by boriskaus** [comment]
I don’t understand why a free surface should affect this. Can you elaborate?

**Comment by aelligp** [comment]
It seems there was a problem with initial script, don't actually know what but now everything works with free surface and with compressible rheologies.

**Comment by albert-de-montserrat** [comment]
> I don’t understand why a free surface should affect this. Can you elaborate?

The lack of convergence with free-surface was most likely unrelated to thermal stresses. Last improvements I did for the free surface seem to have fixed the issue.

**Comment by aelligp** [comment]
First look at the 3D setup of thermal stresses with a resolution of 128^3 after 6 time steps. 

\tau_{II }
first3D_plot

**Review by albert-de-montserrat — APPROVED** [review]
Looks great thanks!

**Pull request merged**
